/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKIO_H
#define _MOCKIO_H

#include "IO/IO.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MockIO_Init(void);
void MockIO_Destroy(void);
void MockIO_Verify(void);




#define IO_write_Expect(address, data) IO_write_CMockExpect(__LINE__, address, data)
void IO_write_CMockExpect(UNITY_LINE_TYPE cmock_line, ioAddress address, ioData data);
#define IO_read_ExpectAndReturn(address, cmock_retval) IO_read_CMockExpectAndReturn(__LINE__, address, cmock_retval)
void IO_read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ioAddress address, ioData cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
