/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockIO.h"

static const char* CMockString_IO_read = "IO_read";
static const char* CMockString_IO_write = "IO_write";
static const char* CMockString_address = "address";
static const char* CMockString_data = "data";

typedef struct _CMOCK_IO_write_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  ioAddress Expected_address;
  ioData Expected_data;

} CMOCK_IO_write_CALL_INSTANCE;

typedef struct _CMOCK_IO_read_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  ioData ReturnVal;
  ioAddress Expected_address;

} CMOCK_IO_read_CALL_INSTANCE;

static struct MockIOInstance
{
  CMOCK_MEM_INDEX_TYPE IO_write_CallInstance;
  CMOCK_MEM_INDEX_TYPE IO_read_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockIO_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_IO_write);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.IO_write_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_IO_read);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.IO_read_CallInstance, cmock_line, CMockStringCalledLess);
}

void MockIO_Init(void)
{
  MockIO_Destroy();
}

void MockIO_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void IO_cmock_write(ioAddress address, ioData data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IO_write_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IO_write);
  cmock_call_instance = (CMOCK_IO_write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IO_write_CallInstance);
  Mock.IO_write_CallInstance = CMock_Guts_MemNext(Mock.IO_write_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IO_write,CMockString_address);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_address), (void*)(&address), sizeof(ioAddress), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IO_write,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_data), (void*)(&data), sizeof(ioData), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_IO_write(CMOCK_IO_write_CALL_INSTANCE* cmock_call_instance, ioAddress address, ioData data)
{
  memcpy(&cmock_call_instance->Expected_address, &address, sizeof(ioAddress));
  memcpy(&cmock_call_instance->Expected_data, &data, sizeof(ioData));
}

void IO_write_CMockExpect(UNITY_LINE_TYPE cmock_line, ioAddress address, ioData data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IO_write_CALL_INSTANCE));
  CMOCK_IO_write_CALL_INSTANCE* cmock_call_instance = (CMOCK_IO_write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IO_write_CallInstance = CMock_Guts_MemChain(Mock.IO_write_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IO_write(cmock_call_instance, address, data);
  UNITY_CLR_DETAILS();
}

ioData IO_cmock_read(ioAddress address)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IO_read_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IO_read);
  cmock_call_instance = (CMOCK_IO_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IO_read_CallInstance);
  Mock.IO_read_CallInstance = CMock_Guts_MemNext(Mock.IO_read_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IO_read,CMockString_address);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_address), (void*)(&address), sizeof(ioAddress), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IO_read(CMOCK_IO_read_CALL_INSTANCE* cmock_call_instance, ioAddress address)
{
  memcpy(&cmock_call_instance->Expected_address, &address, sizeof(ioAddress));
}

void IO_read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ioAddress address, ioData cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IO_read_CALL_INSTANCE));
  CMOCK_IO_read_CALL_INSTANCE* cmock_call_instance = (CMOCK_IO_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IO_read_CallInstance = CMock_Guts_MemChain(Mock.IO_read_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IO_read(cmock_call_instance, address);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(ioData));
  UNITY_CLR_DETAILS();
}

